version: '3.1'
services:

  api-service:
    build: .
    command: /bin/sh -c "/app/wait-for-it.sh db:5432 && /app/wait-for-it.sh redis:6379 && /app/api"
    container_name: sadislands-api
    links:
      - db
      - redis
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: recoveryteam
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sadislands
  
  redis:
    image: redis
    container_name: redis
