version: '3.1'
services:

  consul:
    image: consul
    ports:
      - 8500:8500

  api:
    build:
      context: .
      dockerfile: build/docker/server/Dockerfile
    command: ["/app/api"]
    container_name: api
    links:
      - profile
      - session
      - consul
    volumes:
      - ./upload/img:/app/upload/img
    ports:
      - 8080:8080

  profile:
    build:
      context: .
      dockerfile: build/docker/service/profile/Dockerfile
    command: /bin/sh -c "/app/wait-for-it.sh db:5432 && /app/profile"
    container_name: profile
    links:
      - db_profile
      - consul
    ports:
      - 50051:50051

  session:
    build:
      context: .
      dockerfile: build/docker/service/session/Dockerfile
    command: /bin/sh -c "/app/wait-for-it.sh redis:6379 && /app/session"
    container_name: session
    links:
      - redis
      - consul
    ports:
      - 50052:50052

  game:
    build:
      context: .
      dockerfile: build/docker/service/game/Dockerfile
    command: /bin/sh -c "/app/game"
    container_name: game
    links:
      - session
      - profile
      - consul
    ports:
      - 8081:8081
  chat:
    build:
      context: .
      dockerfile: build/docker/service/chat/Dockerfile
    command: /bin/sh -c "/app/wait-for-it.sh db_chat:5433 && /app/chat"
    container_name: chat
    links:
      - db_chat
      - consul
    ports:
      - 8082:8082

  db_profile:
    image: postgres
    container_name: db_profile
    environment:
      POSTGRES_USER: recoveryteam
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sadislands

  db_chat:
    image: postgres
    container_name: db_chat
    environment:
      POSTGRES_USER: recoveryteam
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sadislandschat

  redis:
    image: redis
    container_name: redis
