version: '3.1'
services:

  api-service:
    image: api
    container_name: sadislands-api
    depends_on: 
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: recoveryteam
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sadislands
  
  redis:
    image: redis
    container_name: redis
