// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	Info                 *Info    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UpdateRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type UpdateAvatarRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAvatarRequest) Reset()         { *m = UpdateAvatarRequest{} }
func (m *UpdateAvatarRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAvatarRequest) ProtoMessage()    {}
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{5}
}

func (m *UpdateAvatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAvatarRequest.Unmarshal(m, b)
}
func (m *UpdateAvatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAvatarRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAvatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAvatarRequest.Merge(m, src)
}
func (m *UpdateAvatarRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAvatarRequest.Size(m)
}
func (m *UpdateAvatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAvatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAvatarRequest proto.InternalMessageInfo

func (m *UpdateAvatarRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAvatarRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UpdatePasswordRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordOld          string   `protobuf:"bytes,3,opt,name=passwordOld,proto3" json:"passwordOld,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{6}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPasswordOld() string {
	if m != nil {
		return m.PasswordOld
	}
	return ""
}

type GetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByEmailRequest) Reset()         { *m = GetByEmailRequest{} }
func (m *GetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetByEmailRequest) ProtoMessage()    {}
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{7}
}

func (m *GetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByEmailRequest.Unmarshal(m, b)
}
func (m *GetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByEmailRequest.Merge(m, src)
}
func (m *GetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetByEmailRequest.Size(m)
}
func (m *GetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByEmailRequest proto.InternalMessageInfo

func (m *GetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetByNicknameRequest struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByNicknameRequest) Reset()         { *m = GetByNicknameRequest{} }
func (m *GetByNicknameRequest) String() string { return proto.CompactTextString(m) }
func (*GetByNicknameRequest) ProtoMessage()    {}
func (*GetByNicknameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{8}
}

func (m *GetByNicknameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByNicknameRequest.Unmarshal(m, b)
}
func (m *GetByNicknameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByNicknameRequest.Marshal(b, m, deterministic)
}
func (m *GetByNicknameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByNicknameRequest.Merge(m, src)
}
func (m *GetByNicknameRequest) XXX_Size() int {
	return xxx_messageInfo_GetByNicknameRequest.Size(m)
}
func (m *GetByNicknameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByNicknameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByNicknameRequest proto.InternalMessageInfo

func (m *GetByNicknameRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type GetByEmailAndPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByEmailAndPasswordRequest) Reset()         { *m = GetByEmailAndPasswordRequest{} }
func (m *GetByEmailAndPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*GetByEmailAndPasswordRequest) ProtoMessage()    {}
func (*GetByEmailAndPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{9}
}

func (m *GetByEmailAndPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByEmailAndPasswordRequest.Unmarshal(m, b)
}
func (m *GetByEmailAndPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByEmailAndPasswordRequest.Marshal(b, m, deterministic)
}
func (m *GetByEmailAndPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByEmailAndPasswordRequest.Merge(m, src)
}
func (m *GetByEmailAndPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_GetByEmailAndPasswordRequest.Size(m)
}
func (m *GetByEmailAndPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByEmailAndPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByEmailAndPasswordRequest proto.InternalMessageInfo

func (m *GetByEmailAndPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetByEmailAndPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{10}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListResponse struct {
	List                 []*Info  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{11}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetList() []*Info {
	if m != nil {
		return m.List
	}
	return nil
}

type CountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{12}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Info struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Score                *Score   `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{13}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Info) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Info) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Info) GetScore() *Score {
	if m != nil {
		return m.Score
	}
	return nil
}

type Score struct {
	Record               int64    `protobuf:"varint,1,opt,name=Record,proto3" json:"Record,omitempty"`
	Win                  int64    `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`
	Loss                 int64    `protobuf:"varint,3,opt,name=loss,proto3" json:"loss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Score) Reset()         { *m = Score{} }
func (m *Score) String() string { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()    {}
func (*Score) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{14}
}

func (m *Score) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Score.Unmarshal(m, b)
}
func (m *Score) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Score.Marshal(b, m, deterministic)
}
func (m *Score) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Score.Merge(m, src)
}
func (m *Score) XXX_Size() int {
	return xxx_messageInfo_Score.Size(m)
}
func (m *Score) XXX_DiscardUnknown() {
	xxx_messageInfo_Score.DiscardUnknown(m)
}

var xxx_messageInfo_Score proto.InternalMessageInfo

func (m *Score) GetRecord() int64 {
	if m != nil {
		return m.Record
	}
	return 0
}

func (m *Score) GetWin() int64 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *Score) GetLoss() int64 {
	if m != nil {
		return m.Loss
	}
	return 0
}

type UpdateRatingRequest struct {
	Winner               uint64   `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"`
	Loser                uint64   `protobuf:"varint,2,opt,name=loser,proto3" json:"loser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRatingRequest) Reset()         { *m = UpdateRatingRequest{} }
func (m *UpdateRatingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRatingRequest) ProtoMessage()    {}
func (*UpdateRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{15}
}

func (m *UpdateRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRatingRequest.Unmarshal(m, b)
}
func (m *UpdateRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRatingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRatingRequest.Merge(m, src)
}
func (m *UpdateRatingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRatingRequest.Size(m)
}
func (m *UpdateRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRatingRequest proto.InternalMessageInfo

func (m *UpdateRatingRequest) GetWinner() uint64 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *UpdateRatingRequest) GetLoser() uint64 {
	if m != nil {
		return m.Loser
	}
	return 0
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{16}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*GetResponse)(nil), "GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateAvatarRequest)(nil), "UpdateAvatarRequest")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "UpdatePasswordRequest")
	proto.RegisterType((*GetByEmailRequest)(nil), "GetByEmailRequest")
	proto.RegisterType((*GetByNicknameRequest)(nil), "GetByNicknameRequest")
	proto.RegisterType((*GetByEmailAndPasswordRequest)(nil), "GetByEmailAndPasswordRequest")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*CountResponse)(nil), "CountResponse")
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*Score)(nil), "Score")
	proto.RegisterType((*UpdateRatingRequest)(nil), "UpdateRatingRequest")
	proto.RegisterType((*Nothing)(nil), "Nothing")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x9b, 0xb4, 0xdb, 0x6e, 0x3f, 0x80, 0x4b, 0x37, 0x95, 0x68, 0x48, 0x93, 0x61, 0xd2,
	0x26, 0x24, 0x0b, 0x15, 0xc4, 0x0b, 0x02, 0x69, 0x4c, 0x63, 0x42, 0x42, 0x63, 0x04, 0xf1, 0xc8,
	0x43, 0x68, 0xdd, 0xcd, 0x90, 0xd9, 0x25, 0xf6, 0xa8, 0xf8, 0x27, 0xfc, 0x5c, 0x64, 0x3b, 0x69,
	0x9c, 0x36, 0xdd, 0x0b, 0x6f, 0x39, 0xb6, 0xef, 0xd7, 0xf1, 0x39, 0x0e, 0xf4, 0xe7, 0x99, 0x9c,
	0xf1, 0x94, 0xd1, 0x79, 0x26, 0xb5, 0x24, 0xfb, 0x00, 0xe7, 0x4c, 0xc7, 0xec, 0xd7, 0x2d, 0x53,
	0x1a, 0x07, 0xd0, 0xe2, 0xd3, 0x51, 0xf3, 0xa0, 0x79, 0x14, 0xc6, 0x2d, 0x3e, 0x25, 0x6f, 0xa1,
	0x6b, 0x77, 0xd5, 0x5c, 0x0a, 0xc5, 0xf0, 0x11, 0x84, 0x5c, 0xcc, 0xa4, 0x3d, 0xd0, 0x1d, 0xb7,
	0xe9, 0x07, 0x31, 0x93, 0xb1, 0x5d, 0xc2, 0x21, 0xb4, 0xd9, 0x4d, 0xc2, 0xd3, 0x51, 0xeb, 0xa0,
	0x79, 0xb4, 0x13, 0x3b, 0x40, 0xbe, 0x41, 0xff, 0x34, 0x63, 0x89, 0x66, 0x45, 0x81, 0xe5, 0xb1,
	0xa6, 0x77, 0x0c, 0x23, 0xd8, 0x16, 0x7c, 0xf2, 0x53, 0x24, 0x37, 0x2c, 0x8f, 0x5f, 0x62, 0xb3,
	0x37, 0x4f, 0x94, 0x5a, 0xc8, 0x6c, 0x3a, 0x0a, 0xdc, 0x5e, 0x81, 0xc9, 0x0f, 0x18, 0x14, 0xe9,
	0xf3, 0x0e, 0x57, 0x06, 0xa8, 0x6f, 0xab, 0x52, 0x2f, 0x58, 0xa9, 0xb7, 0x07, 0x9d, 0xe4, 0x77,
	0xa2, 0x93, 0x6c, 0x14, 0xda, 0x9d, 0x1c, 0x91, 0xcf, 0xd0, 0xff, 0x3a, 0x9f, 0x7a, 0xa3, 0xfc,
	0x77, 0x29, 0xf2, 0x06, 0x1e, 0xba, 0x94, 0x27, 0xb6, 0xc4, 0xa6, 0xc4, 0x65, 0x47, 0xad, 0x4a,
	0x47, 0x0c, 0x76, 0x5d, 0xf8, 0x65, 0xce, 0xc7, 0xa6, 0x04, 0x3e, 0x85, 0xad, 0x2a, 0x85, 0x78,
	0x00, 0xdd, 0xe2, 0xfb, 0x53, 0x5a, 0x30, 0xec, 0x2f, 0x91, 0x63, 0x78, 0x70, 0xce, 0xf4, 0xbb,
	0x3f, 0x67, 0x66, 0x9e, 0x3b, 0xef, 0x91, 0x8c, 0x61, 0x68, 0x8f, 0x5e, 0xe4, 0x13, 0x16, 0xa7,
	0x7d, 0x12, 0x9a, 0x2b, 0x24, 0x5c, 0xc2, 0x7e, 0x99, 0xfe, 0x44, 0x4c, 0x57, 0x87, 0xd9, 0xa8,
	0x98, 0x4d, 0x23, 0x91, 0xd7, 0xd0, 0xfd, 0xc8, 0x95, 0xf6, 0x12, 0xa4, 0xfc, 0x86, 0x6b, 0x9b,
	0x20, 0x88, 0x1d, 0x30, 0xa4, 0xca, 0xd9, 0x4c, 0x31, 0x6d, 0xc3, 0x83, 0x38, 0x47, 0xe4, 0x18,
	0x7a, 0x2e, 0xb8, 0x94, 0x7c, 0xca, 0x95, 0x09, 0x0e, 0x3c, 0xc9, 0x9b, 0x25, 0x72, 0x08, 0xfd,
	0x53, 0x79, 0x2b, 0xca, 0xb3, 0x43, 0x68, 0x4f, 0xcc, 0x42, 0x51, 0xc9, 0x02, 0x72, 0x0d, 0xa1,
	0x09, 0xaa, 0xbb, 0x95, 0x8d, 0xa2, 0x2f, 0xaf, 0x3c, 0xf0, 0xaf, 0x1c, 0xf7, 0xa1, 0xad, 0x26,
	0x32, 0x63, 0x56, 0x9b, 0xdd, 0x71, 0x87, 0x7e, 0x31, 0x28, 0x76, 0x8b, 0xe4, 0x0c, 0xda, 0x16,
	0x9b, 0xf0, 0x98, 0x4d, 0x0c, 0x37, 0xae, 0x93, 0x1c, 0xe1, 0x7d, 0x08, 0x16, 0x5c, 0xe4, 0x13,
	0x9b, 0x4f, 0x44, 0x08, 0x53, 0xa9, 0x94, 0x2d, 0x13, 0xc4, 0xf6, 0x9b, 0x9c, 0x16, 0xb2, 0x8c,
	0x13, 0xcd, 0xc5, 0x55, 0xc1, 0xe3, 0x1e, 0x74, 0x16, 0x5c, 0x08, 0x96, 0xe5, 0x33, 0xe4, 0xc8,
	0xf2, 0x2b, 0x15, 0x73, 0xea, 0x0c, 0x63, 0x07, 0xc8, 0x0e, 0x6c, 0x5d, 0x48, 0x7d, 0xcd, 0xc5,
	0xd5, 0xf8, 0x6f, 0x08, 0x5b, 0x97, 0xee, 0xd1, 0x41, 0x02, 0xc1, 0x39, 0xd3, 0xd8, 0xa5, 0xe5,
	0xa3, 0x13, 0xf5, 0xa8, 0xf7, 0xc6, 0x90, 0x06, 0x3e, 0x83, 0x8e, 0x73, 0x35, 0x0e, 0x68, 0xe5,
	0xf5, 0x88, 0xee, 0xd1, 0xaa, 0xdd, 0x49, 0x03, 0x9f, 0x42, 0xc7, 0x35, 0x8b, 0x03, 0x5a, 0xf1,
	0x67, 0xb4, 0x4d, 0xf3, 0x06, 0x48, 0x03, 0x9f, 0x43, 0xcf, 0x77, 0x1a, 0x0e, 0x69, 0x8d, 0xf1,
	0x2a, 0x11, 0x2f, 0x61, 0x50, 0x35, 0x17, 0xee, 0xd1, 0x5a, 0xb7, 0xad, 0xd4, 0x81, 0x52, 0xcc,
	0x88, 0x74, 0xcd, 0x38, 0x6b, 0xc3, 0xbe, 0x82, 0x7e, 0xc5, 0x32, 0xb8, 0x4b, 0xeb, 0x2c, 0xb4,
	0x16, 0xf7, 0x1e, 0x76, 0x6b, 0x6d, 0x83, 0x8f, 0xe9, 0x5d, 0x76, 0x5a, 0xcb, 0x73, 0x08, 0xa1,
	0xd1, 0x3b, 0xf6, 0xa8, 0xe7, 0x99, 0xa8, 0x4f, 0x7d, 0x13, 0x90, 0x06, 0x3e, 0x81, 0xb6, 0xd5,
	0x3a, 0x2e, 0xa7, 0x8d, 0x06, 0xb4, 0xa2, 0x7e, 0x9f, 0x65, 0x27, 0x9c, 0x25, 0xcb, 0x15, 0x1d,
	0xf9, 0x7c, 0x7d, 0xef, 0xd8, 0x9f, 0xd0, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x0f,
	0xf3, 0xdd, 0x95, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Nothing, error)
	UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...grpc.CallOption) (*Nothing, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*Nothing, error)
	GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetByNickname(ctx context.Context, in *GetByNicknameRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetByEmailAndPassword(ctx context.Context, in *GetByEmailAndPasswordRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Count(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*CountResponse, error)
	UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*Nothing, error)
}

type profileClient struct {
	cc *grpc.ClientConn
}

func NewProfileClient(cc *grpc.ClientConn) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Profile/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/Profile/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/Profile/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateAvatar(ctx context.Context, in *UpdateAvatarRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/Profile/UpdateAvatar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/Profile/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Profile/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetByNickname(ctx context.Context, in *GetByNicknameRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Profile/GetByNickname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) GetByEmailAndPassword(ctx context.Context, in *GetByEmailAndPasswordRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/Profile/GetByEmailAndPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/Profile/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) Count(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/Profile/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) UpdateRating(ctx context.Context, in *UpdateRatingRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/Profile/UpdateRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
type ProfileServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*Nothing, error)
	UpdateAvatar(context.Context, *UpdateAvatarRequest) (*Nothing, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*Nothing, error)
	GetByEmail(context.Context, *GetByEmailRequest) (*GetResponse, error)
	GetByNickname(context.Context, *GetByNicknameRequest) (*GetResponse, error)
	GetByEmailAndPassword(context.Context, *GetByEmailAndPasswordRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Count(context.Context, *Nothing) (*CountResponse, error)
	UpdateRating(context.Context, *UpdateRatingRequest) (*Nothing, error)
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/UpdateAvatar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateAvatar(ctx, req.(*UpdateAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetByEmail(ctx, req.(*GetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetByNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetByNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/GetByNickname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetByNickname(ctx, req.(*GetByNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_GetByEmailAndPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEmailAndPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetByEmailAndPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/GetByEmailAndPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetByEmailAndPassword(ctx, req.(*GetByEmailAndPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).Count(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_UpdateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).UpdateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profile/UpdateRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).UpdateRating(ctx, req.(*UpdateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Profile_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Profile_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Profile_Update_Handler,
		},
		{
			MethodName: "UpdateAvatar",
			Handler:    _Profile_UpdateAvatar_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Profile_UpdatePassword_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _Profile_GetByEmail_Handler,
		},
		{
			MethodName: "GetByNickname",
			Handler:    _Profile_GetByNickname_Handler,
		},
		{
			MethodName: "GetByEmailAndPassword",
			Handler:    _Profile_GetByEmailAndPassword_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Profile_List_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Profile_Count_Handler,
		},
		{
			MethodName: "UpdateRating",
			Handler:    _Profile_UpdateRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
