// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-03-09 14:18:28.125817 +0300 MSK m=+0.169616680

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "127.0.0.1:8080",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/avatars": {
            "put": {
                "description": "Update profile avatar",
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "Put avatar",
                "operationId": "put-avatar",
                "parameters": [
                    {
                        "description": "Avatar",
                        "name": "avatar",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Profile avatar is updated successfully"
                    },
                    "400": {
                        "description": "Incorrect request data"
                    },
                    "403": {
                        "description": "Not authorized"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/profiles": {
            "get": {
                "description": "Check profile existence with email or nickname",
                "summary": "Get profiles",
                "operationId": "get-profiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Profile email",
                        "name": "email",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Profile nickname",
                        "name": "nickname",
                        "in": "path"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Profile found successfully"
                    },
                    "403": {
                        "description": "Not authorized"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            },
            "post": {
                "description": "Create profile",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Post profile",
                "operationId": "post-profile",
                "parameters": [
                    {
                        "description": "Email, nickname, password",
                        "name": "profile_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ProfileInfo"
                        }
                    },
                    {
                        "description": "Avatar",
                        "name": "avatar",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile created successfully",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Profile"
                        }
                    },
                    "400": {
                        "description": "Incorrect request data"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/profiles/{id}": {
            "get": {
                "description": "Get profile info (for profile owner returns info with email)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get profile",
                "operationId": "get-profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Profile found successfully",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Profile"
                        }
                    },
                    "403": {
                        "description": "Not authorized"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            },
            "put": {
                "description": "Update profile info",
                "consumes": [
                    "application/json"
                ],
                "summary": "Put profile",
                "operationId": "put-profile",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Email, nickname, password",
                        "name": "profile_info",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ProfileInfo"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Profile info is updated successfully"
                    },
                    "400": {
                        "description": "Incorrect request data"
                    },
                    "403": {
                        "description": "Not authorized"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/scores": {
            "get": {
                "description": "Get scoreboard",
                "produces": [
                    "application/json"
                ],
                "summary": "Get scoreboard",
                "operationId": "get-scoreboard",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "limit number",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "start index",
                        "name": "start",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scoreboard found successfully",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Profiles"
                        }
                    },
                    "500": {
                        "description": "Database error"
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "description": "Get profile id of authorized client",
                "produces": [
                    "application/json"
                ],
                "summary": "Get session",
                "operationId": "get-session",
                "responses": {
                    "200": {
                        "description": "Profile ID found successfully",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "403": {
                        "description": "Not authorized"
                    }
                }
            },
            "post": {
                "description": "Creates client session",
                "consumes": [
                    "application/json"
                ],
                "summary": "Post session",
                "operationId": "post-session",
                "parameters": [
                    {
                        "description": "Email, password",
                        "name": "profile_login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.ProfileLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session is created successfully"
                    },
                    "400": {
                        "description": "Incorrect request data"
                    },
                    "403": {
                        "description": "Not authorized"
                    },
                    "422": {
                        "description": "Unprocessable request data"
                    }
                }
            },
            "delete": {
                "description": "Deletes client session",
                "summary": "Delete session",
                "operationId": "delete-session",
                "responses": {
                    "200": {
                        "description": "Session is deleted successfully"
                    },
                    "403": {
                        "description": "Not authorized"
                    },
                    "404": {
                        "description": "Session not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Profile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "test@mail.ru"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "loss": {
                    "type": "integer",
                    "example": 50
                },
                "nickname": {
                    "type": "string",
                    "example": "test"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "record": {
                    "type": "integer",
                    "example": 1500
                },
                "win": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "models.ProfileInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@mail.ru"
                },
                "nickname": {
                    "type": "string",
                    "example": "test"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "models.ProfileLogin": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "models.Profiles": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "avatar": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string",
                        "example": "test@mail.ru"
                    },
                    "id": {
                        "type": "integer",
                        "example": 1
                    },
                    "loss": {
                        "type": "integer",
                        "example": 50
                    },
                    "nickname": {
                        "type": "string",
                        "example": "test"
                    },
                    "password": {
                        "type": "string",
                        "example": "password"
                    },
                    "record": {
                        "type": "integer",
                        "example": 1500
                    },
                    "win": {
                        "type": "integer",
                        "example": 100
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
